---
name: Build artifacts for deployment when you push a commit or tag

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build:
    name: Build artifacts in dist folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install compatible NPM version
        run: npm install -g npm@^6
      - name: Install project dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
        env:
          BASE_API_URL: "${{ secrets.VUE_BASE_API_URL }}"
      - name: Preserve build artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/
          name: atat-web-ui
